class Exception:
    def __init__(self,msg, code):
        print(f"Error {code}: {msg}")